# -*- coding: utf-8 -*-
"""«New Kyiv» — a from-scratch surface network generated by greedy optimisation,
the Kyiv analog of London's optimal_network ("New London").

Demand mass per ~500 m cell = calibrated residents (OSM buildings x official
district populations, as in build_density_map.py) + OSM attraction weights.
1) Stations: repeatedly place a station on the cell with the highest uncovered
   mass; coverage within R_COVER discounts mass to 15% (residual).
2) Lines: seed at the highest-mass unassigned station, extend greedily both ways
   to the nearest unassigned station within LINK_KM (preferring mass per km),
   until the line reaches its length cap. Repeat for up to MAX_LINES.
Compared against the real network's stop coverage on the same mass grid."""
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "kyiv_new_network_map.html"

CELL_LAT = 0.0045
CELL_LON = 0.0070
KMLAT = 111.32
KMLON = 111.32 * math.cos(math.radians(50.45))
R_COVER = 0.6      # km — station catchment
RESIDUAL = 0.15
N_STATIONS = 250
LINK_KM = 2.2
LINE_LEN = (8, 16)
MAX_LINES = 30

DISTRICTS = [
    ("Голосіївський", 247600, 50.3565, 30.5210),
    ("Дарницький", 314700, 50.4021, 30.6550),
    ("Деснянський", 358300, 50.5265, 30.6110),
    ("Дніпровський", 354700, 50.4520, 30.6110),
    ("Оболонський", 319000, 50.5060, 30.4980),
    ("Печерський", 152000, 50.4230, 30.5470),
    ("Подільський", 198100, 50.4860, 30.4410),
    ("Святошинський", 340700, 50.4570, 30.3720),
    ("Солом'янський", 383259, 50.4270, 30.4700),
    ("Шевченківський", 218900, 50.4600, 30.4880),
]


def dist_km(a, b):
    return math.hypot((a[0] - b[0]) * KMLAT, (a[1] - b[1]) * KMLON)


# --- demand mass grid: calibrated residents + destinations ---
bldgs = json.loads((BASE / "data" / "residential_osm.json").read_text(encoding="utf-8"))
med_lv = {t: statistics.median([b["lv"] for b in bldgs if b["t"] == t and b["lv"]] or [5])
          for t in {b["t"] for b in bldgs}}
cells = defaultdict(float)
for b in bldgs:
    cells[(round(b["lat"] / CELL_LAT), round(b["lon"] / CELL_LON))] += b["lv"] or med_lv[b["t"]]

def nearest_district(lat, lon):
    return min(range(len(DISTRICTS)),
               key=lambda i: math.hypot((lat - DISTRICTS[i][2]) * KMLAT,
                                        (lon - DISTRICTS[i][3]) * KMLON))

d_weight = defaultdict(float)
cell_d = {}
for c, w in cells.items():
    di = nearest_district(c[0] * CELL_LAT, c[1] * CELL_LON)
    cell_d[c] = di
    d_weight[di] += w
scale = {i: DISTRICTS[i][1] / d_weight[i] for i in d_weight}
mass = {c: w * scale[cell_d[c]] for c, w in cells.items()}

dests = json.loads((BASE / "data" / "destinations_osm.json").read_text(encoding="utf-8"))
for d in dests:
    c = (round(d["lat"] / CELL_LAT), round(d["lon"] / CELL_LON))
    mass[c] = mass.get(c, 0.0) + d["w"]

total_mass = sum(mass.values())
cell_pos = {c: (c[0] * CELL_LAT, c[1] * CELL_LON) for c in mass}
print(f"mass grid: {len(mass)} cells, total {total_mass:,.0f}")

# --- greedy station placement ---
work = dict(mass)
stations = []
cell_list = list(work.keys())
for _ in range(N_STATIONS):
    best = max(cell_list, key=lambda c: work[c])
    if work[best] <= 0:
        break
    pos = cell_pos[best]
    covered = 0.0
    for c in cell_list:
        if dist_km(cell_pos[c], pos) <= R_COVER:
            covered += work[c] * (1 - RESIDUAL)
            work[c] *= RESIDUAL
    stations.append({"lat": round(pos[0], 5), "lon": round(pos[1], 5),
                     "mass": round(mass[best]), "gain": covered})

# --- greedy line building ---
unassigned = set(range(len(stations)))
lines = []
while unassigned and len(lines) < MAX_LINES:
    seed = max(unassigned, key=lambda i: stations[i]["gain"])
    line = [seed]
    unassigned.discard(seed)
    for end in (0, -1):   # extend tail then head
        while len(line) < LINE_LEN[1]:
            tip = stations[line[end]]
            cands = [(i, dist_km((tip["lat"], tip["lon"]),
                                 (stations[i]["lat"], stations[i]["lon"])))
                     for i in unassigned]
            cands = [(i, d) for i, d in cands if d <= LINK_KM]
            if not cands:
                break
            i, d = max(cands, key=lambda x: stations[x[0]]["gain"] / max(x[1], 0.3))
            if end == 0:
                line.insert(0, i)
            else:
                line.append(i)
            unassigned.discard(i)
    if len(line) >= LINE_LEN[0]:
        lines.append(line)
    # short fragments: stations stay placed but line is discarded

# coverage KPI on the original mass: optimal stations vs real stops
def coverage(points, radius):
    cov = 0.0
    for c, m in mass.items():
        p = cell_pos[c]
        if any(dist_km(p, q) <= radius for q in points):
            cov += m
    return cov / total_mass

opt_pts = [(s["lat"], s["lon"]) for s in stations]
stops_all = json.loads((BASE / "data" / "stops_all.geojson").read_text(encoding="utf-8-sig"))
real_pts = [(f["geometry"]["coordinates"][1], f["geometry"]["coordinates"][0])
            for f in stops_all["features"] if f.get("geometry", {}).get("type") == "Point"]
ms = json.loads((BASE / "data" / "metro_stations.geojson").read_text(encoding="utf-8-sig"))
real_pts += [(f["geometry"]["coordinates"][1], f["geometry"]["coordinates"][0])
             for f in ms["features"] if f.get("geometry", {}).get("type") == "Point"]

cov_opt = coverage(opt_pts, R_COVER)
cov_real = coverage(real_pts, R_COVER)
print(f"coverage within {R_COVER} km: optimal {100*cov_opt:.1f}% ({len(opt_pts)} stations) "
      f"vs real {100*cov_real:.1f}% ({len(real_pts)} stops)")

PALETTE = ["#60a5fa","#4ade80","#fbbf24","#f472b6","#a78bfa","#5eead4","#fb7185","#fdba74",
           "#93c5fd","#86efac","#fde047","#f9a8d4","#c4b5fd","#99f6e4","#fca5a5","#fed7aa"]
lines_json = [{"c": PALETTE[i % len(PALETTE)],
               "path": [[stations[s]["lat"], stations[s]["lon"]] for s in ln],
               "n": len(ln)} for i, ln in enumerate(lines)]
stations_json = [{"lat": s["lat"], "lon": s["lon"], "m": s["mass"]} for s in stations]
stats = {"stations": len(stations), "lines": len(lines),
         "cov_opt": round(100 * cov_opt, 1), "cov_real": round(100 * cov_real, 1),
         "real_stops": len(real_pts), "r_cover": R_COVER,
         "on_lines": len(stations) - len(unassigned)}

metro = json.loads((BASE / "data" / "metro_lines.geojson").read_text(encoding="utf-8-sig"))
metro_json = [
    {"c": {"Sviatoshynsko-Brovarska": "#E4222C", "Obolonsko-Teremkivska": "#0F63B6",
           "Syretsko-Pecherska": "#00A651"}.get(f["properties"].get("num_r_eng"), "#888"),
     "path": [[round(y, 5), round(x, 5)] for x, y in f["geometry"]["coordinates"]]}
    for f in metro["features"] if f.get("geometry", {}).get("type") == "LineString"
]

TEMPLATE = (BASE / "scripts" / "new_kyiv_template.html").read_text(encoding="utf-8")
html = (TEMPLATE
        .replace("__LINES__", json.dumps(lines_json))
        .replace("__STATIONS__", json.dumps(stations_json))
        .replace("__METRO__", json.dumps(metro_json))
        .replace("__STATS__", json.dumps(stats, ensure_ascii=False)))
OUT.write_text(html, encoding="utf-8")
print(f"written {OUT}")
